
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: system
spec:
  ports:
    - port: 443
      targetPort: webhook-server
  selector:
    control-plane: cluster-api-kubeadm-control-plane-controller-manager
