[book]
authors = ["The Cluster API Maintainers"]
language = "en"
multilingual = false
src = "src"
title = "The Cluster API Book"

[output.html]
curly-quotes = true
git-repository-url = "https://sigs.k8s.io/cluster-api"

[preprocessor.tabulate]
command = "./util-tabulate.sh"

[preprocessor.embed]
command = "./util-embed.sh"

[preprocessor.releaselink]
command = "./util-releaselink.sh"
